Add files via upload
hum-sc/projectoBD pull request #2
Opened 2022-11-26 23:15 UTC by HectorCG8

Creando la factura

2022-11-26 23:54 UTC, hum-sc requested changes
Aqui estan unas observaciones

2022-11-26 23:54 UTC, hum-sc commented on sqlScripts/startup/createFactura.sql
> +CREATE OR REPLACE PROCEDURE pr_calcular_iva (numfac factura.num_fac%TYPE)
hazlo en un trigger para que se ejecute automaticamente cuando se registre una venta

2022-11-26 23:54 UTC, hum-sc commented on sqlScripts/startup/createFactura.sql
> +    dbms_output.put_line('PRODUCTO'
aqui en lugar de imprimirlo lo debes guardar en las respectivas tablas

2022-11-26 23:54 UTC, hum-sc commented on sqlScripts/startup/createFactura.sql
> +CREATE OR REPLACE PROCEDURE createFactura(numV IN VARCHAR2, fechaV DATE, subV IN NUMBER,
Te recomendaria que el subtotal , iva y total lo dejes en 0, al igual que utilices `FACTURA.<NOMBRECOLUMNA>%TYPE` para asignar los tipos de dato de los parametros

2022-11-26 23:54 UTC, hum-sc commented on sqlScripts/startup/createFactura.sql
> +
Faltaria el procedimiento para crear venta

2022-11-27 00:15 UTC, HectorCG8 commented
que estoy menso dices @hum-sc

2022-11-27 01:33 UTC, hum-sc approved these changes
Todo correcto

2022-11-27 01:33 UTC, merged